//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUMUON
    {
        public string MaCTPM { get; set; }
        public string MaSach { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public bool XoaCTPM { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
