//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCGIA
    {
        public DOCGIA()
        {
            this.PHIEUMUONs = new HashSet<PHIEUMUON>();
        }
    
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Khoa { get; set; }
        public string Lop { get; set; }
        public bool XoaDocGia { get; set; }
    
        public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }
    }
}
