//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUDANGNHAP
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public System.DateTime TGDangNhap { get; set; }
        public bool XoaLS { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
