//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        public PHIEUMUON()
        {
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
            this.PHIEUTRAs = new HashSet<PHIEUTRA>();
        }
    
        public string MaPM { get; set; }
        public int SoLuongMuon { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public string MaDocGia { get; set; }
        public string MaNV { get; set; }
        public bool XoaPM { get; set; }
        public System.DateTime NgayTra { get; set; }
    
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual ICollection<PHIEUTRA> PHIEUTRAs { get; set; }
    }
}
