//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THELOAI
    {
        public THELOAI()
        {
            this.DAUSACHes = new HashSet<DAUSACH>();
        }
    
        public string MaTheLoai { get; set; }
        public string TenTheLoai { get; set; }
        public bool XoaTheLoai { get; set; }
    
        public virtual ICollection<DAUSACH> DAUSACHes { get; set; }
    }
}
